[project]
name = "pamalytics"
version = "1.0.0rc1"
description = "An open source, no-code, classifier-agnostic, interactive dashboard to efficiently review bioacoustic classifier results."
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "Alastair Pickering" }]
dependencies = [
    "altair>=5.0",
    "librosa>=0.10.1",
    "matplotlib>=3.7",
    "numba>=0.59,<0.61",
    "numpy>=1.26,<2.0",
    "openpyxl>=3.1",
    "pandas>=2.0",
    "plotly>=5.0",
    "pydeck>=0.8",
    "pyproj>=3.6",
    "scipy>=1.11,<1.14",
    "soundfile>=0.12.1",
    "streamlit>=1.33,<2",
    "tqdm>=4.66",
]

[project.optional-dependencies]
packaging = ["pyinstaller>=6.0"]
