[project]
name = "pamalytics"
version = "0.1.0"
description = "An open source, no-code, classifier-agnostic, interactive dashboard to efficiently review bioacoustic classifier results."
readme = "README.md"
requires-python = ">=3.12,<3.13"
authors = [{ name = "Alastair Pickering" }]
dependencies = [
  "altair>=5.0",
  "librosa>=0.10.1",
  "matplotlib>=3.7",
  "numpy>=1.26,<2.0",
  "openpyxl>=3.1",
  "pandas>=2.0",
  "pydeck>=0.8",
  "pyproj>=3.6",
  "scikit-learn>=1.4,<1.6",
  "scipy>=1.11,<1.14",
  "soundfile>=0.12.1",
  "streamlit>=1.33",
  "tqdm>=4.66",
]

[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"


[project.scripts]
pamalytics = "pamalytics.main:run"
